{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red98\green98\blue98;\red196\green207\blue212;\red29\green38\blue42;
}
{\*\expandedcolortbl;;\cssrgb\c45882\c45882\c45882;\cssrgb\c81176\c84706\c86275;\cssrgb\c14902\c19608\c21961;
}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sa200\partightenfactor0

\f0\fs30 \cf2 \expnd0\expndtw0\kerning0
\
\pard\pardeftab720\partightenfactor0

\f1\fs26 \cf3 \cb4 # deployment.yaml\
\
apiVersion: apps/v1\
kind: Deployment\
metadata:\
  name: flask-rest-hello-world-deploy\
  labels:\
    type: restapi\
spec:\
  selector: \
    matchLabels:\
      app: flask-rest-hello-world\
  replicas: 3\
  template:\
    metadata:\
      name: flask-rest-hello-world-tmpl\
      labels:\
        app: flask-rest-hello-world\
    spec:\
      containers:\
        - name: flask-rest-hello-world\
          image: flask-rest-hello-world:latest\
          ports:\
            - containerPort: 5000}